# docker-compose.prod.yml

version: '3.8'

networks:
  production_network: # Mạng riêng cho production

services:
  redis:
    image: redis:7-alpine
    container_name: map-app-redis-prod
    restart: unless-stopped
    networks:
      - production_network

  backend:
    image: august0508/map-app-backend:latest
    container_name: map-app-backend-prod
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - production_network

  frontend:
    image: august0508/map-app-frontend:latest
    container_name: map-app-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - production_network
