# docker-compose.yml

services:
  # Redis for pub/sub and caching
  redis:
    image: redis:7-alpine
    container_name: map-app-redis
    restart: unless-stopped
    networks:
      - map-app-network

  # Dịch vụ Backend
  backend:
    build:
      context: ./map-server/backend
    container_name: map-app-backend
    restart: unless-stopped
    ports:
      # Ánh xạ port 4000 của container ra port 4000 của server
      - "4000:4000"
    environment:
      # Nạp các biến môi trường từ file .env ở thư mục gốc
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - SESSION_NAME=${SESSION_NAME}
      - FRONTEND_URL=${FRONTEND_URL}
      - RECAPTCHA_V3_SECRET_KEY=${RECAPTCHA_V3_SECRET_KEY}
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - map-app-network

  # Dịch vụ Frontend
  frontend:
    build:
      context: ./map-server/frontend
    container_name: map-app-frontend
    restart: unless-stopped
    ports:
      # Ánh xạ port 3000 của host ra port 80 của container (Nginx)
      - "3000:80"
    depends_on:
      - backend # Khởi động sau khi backend đã sẵn sàng (tùy chọn)
    networks:
      - map-app-network

# Định nghĩa mạng chung để các container có thể giao tiếp với nhau
networks:
  map-app-network:
    driver: bridge