server {
    listen 80;
    
    gzip on;
    gzip_types text/plain application/javascript text/css;

    # 1. Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. API Backend (SỬA LẠI: Gom tất cả vào /api)
    # Frontend gọi /api/auth/login -> Backend nhận /api/auth/login
    location /api/ {
        proxy_pass http://backend:4000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Ảnh Avatar (Backend lưu trong public/avatars)
    # Frontend gọi /avatars/abc.png -> Backend nhận /avatars/abc.png
    location /avatars/ {
        proxy_pass http://backend:4000;
        proxy_set_header Host $host;
    }

    # 4. Socket.IO (Giữ nguyên)
    location /socket.io/ {
        proxy_pass http://backend:4000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
